### ISSUE TITLE
Does this support :placeholder-shown?

### ISSUE THREAD

**Issue by corysimmons** [ginader/HTML5-placeholder-polyfill#71]
It'd be awfully sweet if it did. :O

**Comment by ginader** [comment]
Hey Cory,
thanks for the great suggestion!
I agree it would indeed be rather sweet!
It is, however, sadly impossible to polyfill the exact :syntax.
What I *can* and will do is to apply a class .placeholder-shown instead.
I'll implement this ASAP.
Wouldn't that be awefully sweet as well?

**Comment by corysimmons** [comment]
I suppose.

How does Selectivizr and stuff work if we can't polyfill pseudos?

**Comment by ginader** [comment]
What Selectivizr is doing is to read all the linked stylesheets and
duplicate the rules that apply to the pseudo selectors and then rewrite the
CSS. This works only with CSS linked from the same domain (so it would fail
from CDNs). While this "somewhat works" it's rather flaky (check the last
paragraph on http://selectivizr.com/ ).
I prefer this to be robust.

**Comment by corysimmons** [comment]
I think `.placeholder-shown` can work. So syntax would work like:

```scss
input {
  &.placeholder-shown,
  &:placeholder-shown {
    background: orange;
  }
}
```

?

**Comment by ginader** [comment]
Exactly! I think this would be very elegant :-)

**Comment by ginader** [comment]
See the new readme section here to see how to use it: https://github.com/ginader/HTML5-placeholder-polyfill#customizing-the-styling-optional

**Comment by corysimmons** [comment]
Awesome. Will be featuring your lib on TutsPlus this upcoming week. Thanks. =)

**Comment by ginader** [comment]
Woohoo! thanks @corysimmons :-)

**Comment by corysimmons** [comment]
No problem. Thanks for being an active/good maintainer. :+1: :100:
